version: '3.9'

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network  # Подключаем к сети

  redis:
    image: redis:7
    expose:
      - 6379
    networks:
      - app-network  # Подключаем к сети

  web:
    build: .
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn --bind 0.0.0.0:8000 yoomoney_project.wsgi:application"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    networks:
      - app-network  # Подключаем к сети

  celery:
    build: .
    command: celery -A yoomoney_project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    networks:
      - app-network  # Подключаем к сети

  celery-beat:
    build: .
    command: celery -A yoomoney_project beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    networks:
      - app-network  # Подключаем к сети

volumes:
  pgdata:

networks:
  app-network:  # Определяем сеть
    driver: bridge  # Используем стандартный драйвер
