version: '3.9'

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "6000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:7
    ports:
      - 6379:6379

volumes:
  pgdata:
